# Generated by Django 3.1.2 on 2021-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='files/static/default-avatar.png', upload_to='users/', verbose_name='profile picture'),
        ),
    ]
