# Generated by Django 3.1.2 on 2021-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default/default-avatar.jpg', help_text='only images formats allowed', upload_to='avatars/', verbose_name='profile picture'),
        ),
    ]
