# Generated by Django 3.1.2 on 2021-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/default-avatar.png', upload_to='users/', verbose_name='profile picture'),
        ),
    ]
