# Generated by Django 3.1.2 on 2021-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210131_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default-avatar.jpg', upload_to='users/', verbose_name='profile picture'),
        ),
    ]
