# Generated by Django 3.1.2 on 2021-01-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20210125_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
    ]
